### PR TITLE
New approach with O(n) time comp.

### PR DESCRIPTION
**Pull request by AMGOcyber123**
### Description

Explain how you solved the coding problem and material you may have referred.

Fixes #(issue_no)

Replace `issue_no` in the above line, with the issue related to this PR.

### Code
```paste_your_language_here

paste_your_code_here

```

Screenshot not visible

To get a screenshot link, upload your screenshot to [postimage](https://postimages.org/) with 'no expiration' and 'do not resize my image' set. Then, copy the `direct link` from there and replace `<screenshot link>` with it.

### Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [ ] I have named my files and folder, according to this project's guidelines.
- [ ] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Solved xyz problem`)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes do not produce any warnings.
- [x] My submission will produce the expected results and not any errors.
- [ ] I have added a working sample/screenshot in this pull request.

### CODE REVIEW

**Comment by ritesh-dt** [comment]
I think we should discuss your solution before creating a pull request. (add your idea of O(n) in the issue page itself)
Also, let's not override somebody else's code.

**Comment by AMGOcyber123** [comment]
Sure @ritesh-dt

**Comment by AMGOcyber123** [comment]
@ritesh-dt  can i redo this problem and create a new PR

**Comment by ritesh-dt** [comment]
But maybe you should choose another language. Python has already been done

**Comment by AMGOcyber123** [comment]
Sure no problem ! Thanks alot !

**Comment by ritesh-dt** [comment]
No problem! Have fun contributing to Hacktoberfest!

**Pull request closed without merging**
