### PR TITLE
Solves Special Array With X Elements Greater Than or Equal X with Cpp

### LINKED ISSUE #18: Special Array With X Elements Greater Than or Equal X
**Title**: Special Array With X Elements Greater Than or Equal X
**Language**: Python

You are given an array nums of non-negative integers. nums is considered special if there exists a number x such that there are exactly x numbers in nums that are greater than or equal to x.

Notice that x does not have to be an element in nums.

Return x if the array is special, otherwise, return -1. It can be proven that if nums is special, the value for x is unique.

https://leetcode.com/problems/special-array-with-x-elements-greater-than-or-equal-x/

**Example 1**
```
Input: nums = [3,5]
Output: 2
Explanation: There are 2 values (3 and 5) that are greater than or equal to 2.
````

**Example 2**
```
Input: nums = [0,0]
Output: -1
Explanation: No numbers fit the criteria for x.
If x = 0, there should be 0 numbers >= x, but there are 2.
If x = 1, there should be 1 number >= x, but there are 0.
If x = 2, there should be 2 numbers >= x, but there are 0.
x cannot be greater since there are only 2 numbers in nums.
````

### PR DESCRIPTION
**Pull request by AryanShinde**
### Description

Explain how you solved the coding problem and material you may have referred.

Fixes #18

Replace `issue_no` in the above line, with the issue related to this PR.

### Code
```CPP

// Special Array With X Elements Greater Than or Equal X
// Aryan Shinde
//
// Approach:
// In this problem, my approach was to sort the given array first and then apllied binary search,
// which compares the numbers with the iteration count and decreases untill their difference doesnt
// get equal to the ierating element, if found, return that or simply return -1 if not found

// Time complexity: O(nlogn)
// Space complexity: O(1)

#include <iostream>
#include <vector>
#include <bits/stdc++.h>

using namespace std;

class Solution
{
public:
    int specialArray(vector<int> &nums)
    {
        sort(nums.begin(), nums.end());
        for (int i = 0; i <= nums.size(); i++)
        {
            int start = 0;
            int end = nums.size() - 1;
            while (start <= end)
            {
                int mid = start + (end - start) / 2;
                if (nums[mid] >= i)
                {
                    end = mid - 1;
                }
                else if (nums[mid] < i)
                {
                    start = mid + 1;
                }
            }
            if (nums.size() - start == i)
            {
                return i;
            }
        }
        return -1;
    }
};
int main()
{
    Solution s;
    vector<int> nums = {0, 4, 3, 0, 4};
    if (s.specialArray(nums) != -1)
        cout << s.specialArray(nums) << endl;
    else
    {
        cout << "element not found";
    }
    return -1;
}
```

Screenshot not visible

To get a screenshot link, upload your screenshot to [postimage](https://postimages.org/) with 'no expiration' and 'do not resize my image'

### Checklist:
Please tick all the boxes that are fulfilled by your Pull Request.

- [x] I have named my files and folder, according to this project's guidelines.
- [x] My code follows the style guidelines of this project.
- [x] My Pull Request has a descriptive title. (not a vague title like `Solved xyz problem`)
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes do not produce any warnings.
- [x] My submission will produce the expected results and not any errors.
- [x] I have added a working sample/screenshot in this pull request.

### CODE REVIEW

**Comment by ritesh-dt** [comment]
Keep the title as 'Solves question title in language' rather than 'Solve issue number...'

**Comment by AryanShinde** [comment]
Sure, Have done the required changes!

**Comment by ritesh-dt** [comment]
@AryanShinde I've updated your pull request comment, please take note of those changes.

**Comment by AryanShinde** [comment]
yess, thank you so much!

**Comment by ritesh-dt** [comment]
@AryanShinde Did the merged pull request show up on your Hacktoberfest dashboard?

**Comment by AryanShinde** [comment]
umm not yet, but i'll revert back once it does, thank you for the merge!

**Comment by ritesh-dt** [comment]
Sure!

**Comment by AryanShinde** [comment]
hey, it got added into progress count and says, matures in 14 days

**Comment by AryanShinde** [comment]
no progress count is, i think hacktoberfest takes 14 days until it gets reviewed again for spam, but yes its not in PR count but progress count

**Comment by ritesh-dt** [comment]
Okay, then get give me an update when I does mature after 14 days

**Comment by AryanShinde** [comment]
Definitely

**Comment by AryanShinde** [comment]
hey @ritesh-dt , i got a message on my profile that this project is excluded from hacktoberfest
image
:(

**Comment by ritesh-dt** [comment]
Yeah, I also got to know about this. Hacktoberfest is quite strict this time around has excluded a lot of repositories on GitHub. 

Did you have any contributions in other repositories?

**Comment by AryanShinde** [comment]
Um yes, but i think you have accidentally removed the ```hacktoberfest``` label from the issue/repo

**Pull request merged**
